### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by GitBruno** [oshwa/certification-mark#20]
Would it make sense to add an explicit licence to this repo?

**Comment by mwweinberg** [comment]
The licensing is a bit complicated because the logo itself is part of the certification process.  We could release the artwork itself under a permissive license, but many obvious uses under that license would likely violate the OSHWA certification trademark.  For now the least confusing way to deal with this seems to be to not add a license to the repo.  I recognize that is somewhat counter intuitive in the general context of open source hardware, and am open to alternative suggestions.  I am concerned that adding a license with a big disclaimer (the other obvious approach) would on balance bring  more confusion than clarity.

**Comment by GitBruno** [comment]
In that case we would need to add an EULA (End User Licence Agreement)

**Comment by mwweinberg** [comment]
The EULA covering the use of the logo is part of the license agreement governing the certification application:

https://certification.oshwa.org/license-agreement.html
